# Generated by Django 2.0 on 2018-03-04 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0002_auto_20180304_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='completed_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('files', models.FileField(upload_to='')),
                ('recommendation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('files', models.FileField(upload_to='')),
                ('direction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('started_on', models.DateTimeField(auto_now_add=True)),
                ('ended_on', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='project',
            field=models.ManyToManyField(to='projectApp.project'),
        ),
        migrations.AddField(
            model_name='part',
            name='worker',
            field=models.ManyToManyField(to='Accounts.Staff'),
        ),
        migrations.AddField(
            model_name='completed_task',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.part'),
        ),
        migrations.AddField(
            model_name='completed_task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.project'),
        ),
    ]
