# Generated by Django 2.0 on 2018-03-04 12:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20180304_1738'),
        ('projectApp', '0002_auto_20180304_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='project',
        ),
        migrations.AddField(
            model_name='part',
            name='project',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='projectApp.project'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='part',
            name='worker',
        ),
        migrations.AddField(
            model_name='part',
            name='worker',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Staff'),
            preserve_default=False,
        ),
    ]
